# config.yaml

# 源代码库路径 (默认填入本地chipyard路径)
source_repo_path: "/home/shiroha/Code/tapeout/source"

# client上生成用于提交到GitHub的代码的输出路径 (默认填入本仓库的路径)
separate_target_path: "/home/shiroha/Code/tapeout/CI-Zipper"

# 文件映射关系
file_mappings:
  - source: "generators/gemmini/"
    target: "src/npu/"
  - source: "workload/"
    target: "workload/"
