# config.yaml

# 源代码库路径 (默认填入本地chipyard路径)
project_path: "/home/shiroha/Code/tapeout/source"

# client上生成用于提交到GitHub的代码的输出路径 (默认填入本仓库的路径)
zipper_path: "/home/shiroha/Code/tapeout/CI-Zipper"

# 文件映射关系
file_mappings:
  - project: "generators/gemmini/"
    zipper: "src/npu/"
  - project: "workload/"
    zipper: "workload/"
